name: jkntestsite33
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8655970667023212
title: This is a test site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1b24'
    - '#ffffff'
    - '#404042'
    - '#818286'
    - '#f25c61'
  brandStrength: 1
  lightness: 0.18439657567068934
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
